/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapAdaptorSol from "./UniswapAdaptor.sol";
export type { uniswapAdaptorSol };
import type * as test from "./test";
export type { test };
