/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface UniswapAdaptorInterface extends utils.Interface {
  functions: {
    "FACTORY_ADDRESS()": FunctionFragment;
    "ROUTER_ADDRESS()": FunctionFragment;
    "createPair(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "FACTORY_ADDRESS" | "ROUTER_ADDRESS" | "createPair"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "FACTORY_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROUTER_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPair",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "FACTORY_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROUTER_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPair", data: BytesLike): Result;

  events: {};
}

export interface UniswapAdaptor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniswapAdaptorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    FACTORY_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    ROUTER_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    createPair(
      _token0: string,
      _token1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  FACTORY_ADDRESS(overrides?: CallOverrides): Promise<string>;

  ROUTER_ADDRESS(overrides?: CallOverrides): Promise<string>;

  createPair(
    _token0: string,
    _token1: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    FACTORY_ADDRESS(overrides?: CallOverrides): Promise<string>;

    ROUTER_ADDRESS(overrides?: CallOverrides): Promise<string>;

    createPair(
      _token0: string,
      _token1: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    FACTORY_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    ROUTER_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    createPair(
      _token0: string,
      _token1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    FACTORY_ADDRESS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ROUTER_ADDRESS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createPair(
      _token0: string,
      _token1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
